// <auto-generated />
namespace Domain.Persistence.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration_City_Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_City_Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201607121144457_migration_City_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
